Don't exit on successful run, only on error.

diff --git a/laborations/lab4/Makefile b/laborations/lab4/Makefile
--- a/laborations/lab4/Makefile
+++ b/laborations/lab4/Makefile
@@ -58,7 +58,7 @@ define generate_sh_runnner =
 	echo "#!/bin/sh" > $(2)
 	$(foreach exec,$(1),(echo "echo [~] Running $(exec)." &&\
 						 echo "echo $(undescore)" &&\
-						 echo "$(exec) || echo "[!] FAILED: $(exec)" && exit"&&\
+						 echo "$(exec) || (echo "[!] FAILED: $(exec)" && exit)"&&\
 						 echo "echo [~] $(exec) DONE."&&\
 						 echo "echo ")\
 						 >> $(2);)
